# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ultimos
description: Testando uma build customizada do bazzite com WMs.
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      cleanup: true
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      copr:
        - faugus/faugus-launcher
        - monkeygold/nautilus-open-any-terminal
        - lionheartp/Hyprland
        
    install:
      install-weak-deps: false
      packages:
        - terra-release
        - nwg-look
        - fish
        - umbriel-nightly
        - kitty
        - nautilus-open-any-terminal
        - adw-gtk3-theme
        - noctalia
        - mpv
        - faugus-launcher
        - xwayland-satellite
        - android-tools
        - niri
        - hyprland
        - hyprland-guiutils
        - brave-origin

        
    remove:
      packages:
        - waydroid
        - waydroid-selinux
        - rom-properties
        - input-remapper
        - malcontent
        - malcontent-control

  - type: signing
