# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ultimos
# description will be included in the image's metadata
description: Testando uma build customizada do bazzite com WMs.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # Adicionando o Terra Repo via arquivo e instalando pacotes
  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      packages:
        - terra-release
        - nwg-look

  # Adicionando repositório Copr e gerenciando pacotes nativos
  - type: dnf
    repos:
      copr:
        - lionheartp/Hyprland
    install:
      packages:
        - adw-gtk3-theme
        - hyprland
        - niri
        - noctalia
        - hyprland-guiutils
        - mpv
        - gwenview 
    remove:
      packages:
        - waydroid
        - waydroid-selinux
        - input-remapper

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
